### ISSUE TITLE
Add/ config CI.CD for publising on Github Pages

### ISSUE THREAD

**Issue by pnguyen215** [pnguyen215/portfolio4next#5]
[How to Deploy Next.js Apps to Github Pages](https://www.freecodecamp.org/news/how-to-deploy-next-js-app-to-github-pages/)
---
```yaml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        env:
          NEXT_PUBLIC_BASE_PATH: "/your-repo-name"
          NEXT_PUBLIC_PAGE_EXTENSIONS: "js,jsx,ts,tsx,md,mdx"
          NEXT_PUBLIC_OUTPUT: "export"
          NEXT_PUBLIC_TS_IGNORE_BUILD_ERRORS: "true"
          NEXT_PUBLIC_ESLINT_IGNORE_DURING_BUILDS: "true"
          NEXT_PUBLIC_REACT_STRICT_MODE: "true"
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
```
